
<div class="article">   
    <h3><?php echo $title; ?></h3>
        
        <?php if($filepath != null): ?>
                  <p><img src=<?="$filepath"; ?> /></p>
        <?php else: ?>
                  <h3>THIS RAN</h3>
                  <p><img src='Images/2002.jpg'/></p>
        <?php endif; ?>
                  
    <p><?php echo $content; ?></p>  
    <p>Posted: <?php echo $date; ?></p>
</div>
