<div class="article">

    <h3><?php echo $title; ?></h3>
        
        <?php if($filepath != null): ?>
                  <img src=<?="$filepath"; ?> />
        <?php else: ?>
                  <h3>THIS RAN</h3>
                  <img src='Images/2002.jpg'/>
        <?php endif; ?>

    <h4>Category: <?php echo $category; ?></h4>  
    <h4>Posted: <?php echo $date; ?></h4>
    <h4>Author: <?php echo $contributor; ?></h4>
    <p><?php echo $content; ?></p>

</div>
