<?php 

namespace Views\Footer;

?>

<footer class="footer">
        <div>
            <a href="http://www.facebook.com" target="_blank" class="fa fa-facebook"></a></br>
                <a href="http://www.twitter.com" target="_blank" class="fa fa-twitter"></a></br>
                <a href="http://www.github.com" target="_blank" class="fa fa-github"></a></br>
                <a href="http://www.instagram.com" target="_blank" class="fa fa-instagram"></a></br>
                <a href="http://www.pinterest.com" target="_blank" class="fa fa-pinterest"></a></br>
        </div>
</footer>
