<?php 

namespace Views\Footer;

?>

<footer class="footer">
        <div>
            <a href="www.facebook.com" class="fa fa-facebook"></a></br>
                <a href="www.twitter.com" class="fa fa-twitter"></a></br>
                <a href="www.github.com" class="fa fa-github"></a></br>
                <a href="www.instagram.com" class="fa fa-instagram"></a></br>
                <a href="www.pinterest.com" class="fa fa-pinterest"></a></br>
        </div>
</footer>
