<form   name="userLogin"
        action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"
        onsubmit="return validateUserLoginForm()"
        method="POST"
        enctype="multipart/form-data">
    
    <div class="login-form">
        
        <!--<h1><label for="username">Username:</label></h1>-->
        <p><input name="username" type="text" placeholder="Username"/></p>
        
        <!--<h1><label for="password">Password:</label></h1>-->
        <p><input name="password" type="password" placeholder="Password"/></p>
        
        <button type="submit" class="button">Log in</button>
        
        <p>Not a member yet?</p>
        
      <h2><a href="signup.php">Sign up</a></h2>
        
    </div>    
    
</form>
    
  