<form action="" method="POST">
    
    <div class="row">
        <div class="form">
         <h1 class="one column">
             <!--<label for="username">Username: </label>-->
             <input name="username" type="text" placeholder="Username"/>
         </h1>

         <h1>
<!--            <label for="password">Password: </label>-->
            <input name="password" type="password" placeholder="Password"/>
         </h1>
          
         <div class="one column">
             <h1>
                 <input type="image" id="loginbutton" src="Images/loginbutton.png"></button>
             </h1>
         </div>

        <div class="one column">
            <a href="signup.php"><img src="Images/signupbutton.png" id="signupbutton"></a></p>
        </div>
        
        </div>
    </div>
    </div>
 
</form>
