<form action="" method="POST">
    
    <div class="row">
        <div class="form">
         <h1 class="one column">
             <label for="username">Username: </label>
             <input name="username" type="text" placeholder="Username"/>
         </h1>

         <h1>
            <label for="password">Password: </label>
            <input name="password" type="password" placeholder="Password"/>
         </h1>
    </div>
        <div class="buttons">
            <button type="submit" id="loginbutton"><img src="Images/loginbutton.png">  
        </div>
        <p> Not already a member?</p>
        <div class="buttons">
            <a href="signup.php"><img src="Images/signupbutton.png" id="signupbutton"></a>
        </div> 
    </div>   
</form>
