<?php 

namespace View\Navbar;

?>   

<header>
    <link rel="stylesheet" href="CSS/styles.css">
    <div id="js-header" class="header">
        <img src="Images/howlogo.png" alt="logo" height="200" width="240"/>
    </div>
    <div class="topnav">
    <ul>
        <li class="align-left"><a href="index.php">Home</a></li>
        
        <!--<li class="align-left"><a href="Cat1">Category 1</a></li>
        <li class="align-left"><a href="Cat2">Category 2</a></li>-->
        
        <?php 
            if ($_SESSION) {
                echo '<li class="align-right"><a href="logout.php">Log Out</a></li>';
                echo '<li class="align-right"><a href="upload.php">Upload</a></li>';
            } else {
                echo '<li class="align-right"><a href="login.php">Log In</a></li>';
            }
        ?>
      
        
    </ul>
    </div>
    <script type="text/javascript" src="JavaScript/js.js"></script>
</header> 
    
    
 
