<?php 

namespace View\Navbar;

?>

<header>
    <div class="topnav">
    <ul>
        <li class="align-left"><a href="index.php">Home</a></li>
        
        <!--<li class="align-left"><a href="Cat1">Category 1</a></li>
        <li class="align-left"><a href="Cat2">Category 2</a></li>-->
        
        <li class="align-right"><a href="login.php">Log In</a></li>
        
        <!--<li class="align-right"><a href="Upload">Upload</a></li>-->
        
    </ul>
    </div>
</header> 
 



