<form   name="userSignup"
        action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"
        onsubmit="return validateUserSignupForm()"
        method="POST"
        enctype="multipart/form-data">
    
    <div class="signup-form">
    
        
        <!--<h1><label for="username">Username: </label></h1>-->
        <p><input name="username" type="text" placeholder="Username"/></p>
        
        <!--<h1><label for="firstname">First Name: </label></h1>-->
        <p><input name="firstname" type="text" placeholder="First Name"/></p>
        
        <!--<h1><label for="lastname">Last Name: </label></h1>-->
        <p><input name="lastname" type="text" placeholder="Last Name"/></p>
       
        <!--<h1><label for="emailaddress">Email Address: </label></h1>-->
        <p><input name="emailaddress" type="text" placeholder="Email"/></p>
        
        <!--<h1><label for="password">Password: </label></h1>-->
        <p><input id="pass1" name="password" type="password" placeholder="Password"/></p>
        <p><input id="pass2" name="password2" type="password" placeholder="Confirm Password"/></p>

        <button type="submit" class="button">Sign up</button>
        
    </div>

</form>