<form   name="userSignup"
        action="signup.php"
        onsubmit="return validateUserSignupForm()"
        method="POST"
        enctype="multipart/form-data">
    
    <div>
        <label for="username">Username: </label>
        <input name="username" type="text"/>
    </div>
    
    <div>
        <label for="firstname">First Name: </label>
        <input name="firstname" type="text"/>
    </div>
    
    <div>
        <label for="lastname">Last Name: </label>
        <input name="lastname" type="text"/>
    </div>
    
    <div>
        <label for="emailaddress">Email Address: </label>
        <input name="emailaddress" type="text"/>
    </div>

    <div>
        <label for="password">Password: </label>
        <input name="password" type="password"/>
    </div>
    
    <div>
        <label for="password2">Password: </label>
        <input name="password2" type="password" placeholder="confirm password"/>
    </div>

    <button type="submit">Sign up</button>

</form>