

<form  name='upload'
       action='upload.php'
       method='post'
       onsubmit="return validateForm()"
       enctype="multipart/form-data">

<input type='hidden'
       name='MAX_FILE_SIZE'
       value ='10000000'/>
      
     Title: <input type='text' name='title' id='title' /><br />
  Category: <select name='category' id='category'>
                <option value="Humblebrag">Humblebrag</option>
                <option value="Handpoured">Handpoured</option>
                <option value="Hipsperation">Hipsperation</option>
            </select><br />
   Content: <textarea  name='content' id='content'></textarea>
     Image: <input type='file' name='userFile'/><br />
            <input type='hidden' name='contributor' value='' />
            <input type='submit' value='Submit' />
</form>


<script>tinymce.init({ selector:'textarea' });</script>
