<form  action="upload.php" 
       method="post"
       enctype="multipart/form-data">

    <input type='hidden'
           name='MAX_FILE_SIZE'
           value ='10000000'/>

    <div class="upload-form">

        <h1><input type='text' name='title' id='title' placeholder="Title"/></h1><br />
        <p>Category: <select name='category' id='category'>
                    <option value="Humblebrag">Humblebrag</option>
                    <option value="Handpoured">Handpoured</option>
                    <option value="Hipsperation">Hipsperation</option>
                    </select></p><br />
                    <h1><textarea  name='content' id='content' placeholder="Content"></textarea>
                    <p>Image: <input type='file' name='userFile' class=""/></p><br />
                    <input type='hidden' name='contributor' value='' />
                    <input type='submit' value='Submit' class="button"/></h1>

    </div>
</form>

<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>