<script>tinymce.init({ selector:'textarea' });</script>

<form   name="upload"
        action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"
        onsubmit="return validateUploadForm()"
        method="POST"
        enctype="multipart/form-data">

<input  type='hidden'
        name='MAX_FILE_SIZE'
        value ='5000000'/>

    <div class="upload-form">

        <h1><input type='text' name='title' id='title' placeholder="Title"/></h1>
        <p>Category: <select name='category' id='category'>
                    <option value=""></option>
                    <option value="Humblebrag">Humblebrag</option>
                    <option value="Handpoured">Handpoured</option>
                    <option value="Hipsperation">Hipsperation</option>
                    </select></p>
                    <textarea  name='content' id='content' placeholder="Content"></textarea>
                    <p>Image: <input type='file' name='userFile' class=""/></p>
                    <input type='hidden' name='contributor' value='' />
                    <input type='submit' value='Submit' class="button"/>

    </div>

</form>
